# Generated by Django 4.2.6 on 2023-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='district',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
